### ISSUE TITLE
Tested and is working. 

### ISSUE THREAD

**Issue by Therrixxe** [scrapcomputing/WavetablePiHoriz#1]
When building it I moved R1 and R2 to the other side just to prevent issues with mounting the raspberry pi zero 2. Spacing is a little tight when mounting the resistors. I have tested the LCD and buttons however I haven't tested the rotary encoder yet. Thank you for making the horizontal version so quickly. 

I have tested it on an ESS ISA card and PicoGUS in MPU-401mode and it works perfectly.

**Comment by scrapcomputing** [comment]
Great! Thanks for the feedback. I will try to fix the spacing for R1 and R2 in a future revision.

**Comment by Therrixxe** [comment]
I have worked up two faceplates for the wavetable header. https://www.thingiverse.com/thing:6652143

One using round buttons and one using 3d printed square buttons. Still need to laser cut the acrylic for the square one. I was going to use the label SC-32_PIWT_ with your logo.

**Comment by scrapcomputing** [comment]
Awesome! Thanks for sharing your project, I will add a link to it in the project's README.
