### ISSUE TITLE
C1 - C4 placement issue with Diamond Monster Sound MX300

### ISSUE THREAD

**Issue by sweetlilmre** [scrapcomputing/WavetablePiHoriz#2]
The position of the C1-C4 capacitors interferes with the CD/AUX/MODEM connectors on this card.
Suggest moving the component to the opposite side of the board, this should be fairly simple, all that would be needed is an update to the silkscreen. See e.g.: ![Diamond Monster Sound MX300](https://soundprogramming.net/images/Soundcard/Diamond-Monster-Sound-MX300.jpg)

**Comment by scrapcomputing** [comment]
Thanks for the feedback. Yeah I might add the silk screen on both sides in a follow up revision. Or perhaps a version with SMD parts would be more suitable.

**Comment by sweetlilmre** [comment]
Just to close this off, swapping the orientation worked well!
![image](https://github.com/user-attachments/assets/867da2ab-915e-41e6-91b1-46005ae4c305)
